name = "NPTFluidEquilibrium"
uuid = "abab5a2f-3416-4f8b-a068-7ddb5dbeea11"
authors = ["Stepan Zakharov <stepanzh@gmail.com>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
